from photo_pipeline import loader
from photo_pipeline import prediction_pipeline
from photo_pipeline import predictor
from photo_pipeline import preprocessor

from photo_pipeline.prediction_pipeline import pipeline_for_folder